#%RAML 1.0
title: Accounts API

/accounts:
  get:
    description: retrieve customer accounts
    headers:
      user_id:
    queryParameters:
      account_type:
        description: filter based on personal or business account
        type: AccountType
        required: false
      account_name:
        description: filter based on the account name
        required: false
    responses:
      200:
        body:
          application/json:
            type: array
            