#%RAML 1.0 NamedExample
value:
    ID: 1 
    name: Brandito's Cafe
    Type: personal
    Address: 12345
    origin: CLE
    destination: SFO
    emptySeats: 0
    plane: 
      type: Boeing 737
      totalSeats: 150