#%RAML 1.0 NamedExample
value:
    ID: 1 
    name: Brandito's Cafe
    ype: personal
    address: 12345 Spooky St, Salem, Massachussets, 01970, USA
    airMiles: CLE
    destination: SFO
    emptySeats: 0
    plane: 
      type: Boeing 737
      totalSeats: 150